name: iOS Build Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-simulator:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build iOS for Simulator
        uses: ./
        with:
          destination: 'simulator'
          scheme: 'YourScheme'
          configuration: 'Debug'
          working-directory: './packages/mobile' # Adjust this path based on your project structure

  build-device:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build iOS for Device
        uses: ./
        with:
          destination: 'device'
          scheme: 'YourScheme'
          configuration: 'Release'
          certificate-base64: ${{ secrets.CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          provisioning-profile-name: 'YourProfileName'
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
          working-directory: './packages/mobile' # Adjust this path based on your project structure
          re-sign: true # Enable re-signing for PR builds 